### ISSUE TITLE
Add cancellation token support

### ISSUE THREAD

**Issue by Lavinski** [Lavinski/Enexure.MicroBus#11]

**Comment by Jaben** [comment]
Funny, was just going to request this...

**Comment by Jaben** [comment]
This would require API changes. Or should this wait till a "next release" to break the API?

**Comment by Lavinski** [comment]
Adding an overload for the main classes would avoid breaking changes (as opposed to adding an optional parameter). Changes to the interfaces would be a breaking change. To avoid that I'd consider adding two new interfaces. Possible names could include async or cancelable.

- ICancelableMicroBus
- ICancelableMediator

**Comment by Jaben** [comment]
What about the receiving end? Event, Command and Query Handlers? IDelegatingHandler?

**Comment by Lavinski** [comment]
The same approach can be taken for them as well. 

The trickiest part is keeping the old delegating handlers working. However, because the next delegating handler is not executed directly it's possible to pass the token along even if the non-cancelling delegating handlers are used.

**Comment by Lavinski** [comment]
Prerelease packages are now on NuGet

**Comment by Jaben** [comment]
Thank you!

**Comment by Lavinski** [comment]
Released as MicroBus 3.5
