### ISSUE TITLE
How to register a MicroBus pre-instantiated Handler

### ISSUE THREAD

**Issue by maiorfi-at-innovactive** [Lavinski/Enexure.MicroBus#16]
Hi.

I'd like to run something like:

```csharp
            _myPreinitializedService=new UsefulCommandHandler("my default value");
            _myPreinitializedService.DoLongInitialization().Wait();

            // AUTOFAC REGISTRATIONS
            _containerBuilder = new ContainerBuilder();
            _containerBuilder.RegisterInstance(_myPreinitializedService).As<UsefulCommandHandler>();

            // BUS
            var busBuilder = new BusBuilder()
                .RegisterCommandHandler<UsefulCommand, UsefulCommandHandler>();

            var container = _containerBuilder.RegisterMicroBus(busBuilder).Build();

            _bus = container.Resolve<IMicroBus>();
```

but, since UsefulCommandHandler has only a non default ctor (taking a string MyParameter parameter)  whenever I call

```csharp
_bus.SendAsync(new UsefulCommand());
```

...I get a:

None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'UsefulCommandHandler' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.String MyParameter' of constructor 'Void .ctor(System.String)'.

Same type resolution before calling:
```csharp
            // BUS
            var busBuilder = new BusBuilder()
                .RegisterCommandHandler<PingParadoxHostCommand, ParadoxServiceProvider>();

            var container = _containerBuilder.RegisterMicroBus(busBuilder).Build();

            _bus = container.Resolve<IMicroBus>();
```
...works as expected (i.e. autofac correctly resolves type with my preinitialized instance).

 What is the proper way to do it?

Thanks!

**Comment by Lavinski** [comment]
Hi @maiorfi-at-innovactive,

Something like this should be possible, I think the issue you're seeing is because when `RegisterMicroBus` is called it will perform its own set of registrations with Autofac. These would then override your earlier call to `RegisterInstance`. 

Moving your registration to after `RegisterMicroBus` should avoid the issue.

**Comment by maiorfi-at-innovactive** [comment]
You're right: swapping registrations works as expected. Following code as a reference for the future 😄 

```csharp
var busBuilder = new BusBuilder()
           .RegisterCommandHandler<MySampleCommand, MySampleCommandHandler>()
           .RegisterCommandHandler<MyOtherSampleCommand, MyOtherSampleCommandHandler>();

var containerBuilder = new ContainerBuilder();
var microbusEnabledContainerBuilder = containerBuilder.RegisterMicroBus(busBuilder);

containerBuilder.RegisterInstance(new MyOtherSampleCommandHandler("initialization state")).As<MyOtherSampleCommandHandler>();

var container = microbusEnabledContainerBuilder.Build();

_bus = container.Resolve<IMicroBus>();
```
