### ISSUE TITLE
Add support for LightInject

### ISSUE THREAD

**Issue by topsey** [Lavinski/Enexure.MicroBus#19]
Hi Daniel,

I have recently been testing both Microbus and Mediatr in a UWP app, I have only managed to get yours to work...

The UWP app utilizes MvvmLight

It would be good to add LightInject, I have it working with Autofac ok.

Ian

**Comment by Lavinski** [comment]
Hi @topsey,

It shouldn't be too hard to get LightInject working. If you want to have a go at it yourself this commit has everything you need to add a container to MicroBus. There's really only three main files which implement  IDependencyResolver, IDependencyScope and the ContainerExtensions.

https://github.com/Lavinski/Enexure.MicroBus/commit/72cf90c25865b2ade45057a460678c8ca947cb61

**Comment by Lavinski** [comment]
LightInject Nuget package added, the container doesn't really support child containers too well but I should still work all tests are green.

56e6cc5a9e88fa18c9b5a70c97c1af46e7ef5d5a
