### ISSUE TITLE
How to use with StructureMap

### ISSUE THREAD

**Issue by thedumbtechguy** [Lavinski/Enexure.MicroBus#22]
I'm leaning towards Microbus over Mediatr. 
The problem is we prefer to use StructureMap and I can't find what I need to make it work with it as all your tutorials speak to Autofac. 

I'd appreciate any help getting this work.

**Comment by Lavinski** [comment]
Hi there,

If you're interested in StructureMap support, I should be able to look into it soon-ish. In the meantime you could check out this commit.

[Add support for Microsoft.Extensions.DependencyInjection](https://github.com/Lavinski/Enexure.MicroBus/commit/72cf90c25865b2ade45057a460678c8ca947cb61) which is a pretty good template for adding a new container.

It may look like a lot but most of it is just a copy of some tests. At the core of the change you only need to implement three files.

[ContainerExtensions.cs](https://github.com/Lavinski/Enexure.MicroBus/commit/72cf90c25865b2ade45057a460678c8ca947cb61#diff-1443d8686e91599ea3842dc4e72e3f7a)
[MicrosoftDependencyInjectionDependencyResolver.cs](https://github.com/Lavinski/Enexure.MicroBus/commit/72cf90c25865b2ade45057a460678c8ca947cb61#diff-a53d55e8f4b88fd5c7afede01592c565)
[MicrosoftDependencyInjectionDependencyScope.cs](https://github.com/Lavinski/Enexure.MicroBus/commit/72cf90c25865b2ade45057a460678c8ca947cb61#diff-cd94d411204c7aed5123353a9adeff97)

**Comment by Lavinski** [comment]
I've added a StructureMap package [Enexure.MicroBus.StructureMap](https://www.nuget.org/packages/Enexure.MicroBus.StructureMap) check it out and let me know how it goes (All tests are green).

Usage is similar to other contains:

    var busBuilder = new BusBuilder()
        .RegisterCommandHandler<Command, CommandHandler>();

    var container = new Container(b => b.RegisterMicroBus(busBuilder));

    var bus = container.GetInstance<IMicroBus>();

**Comment by thedumbtechguy** [comment]
Amazing, thank you.
I'll let you know when I test.

Regards
