### ISSUE TITLE
InvalidDuplicateRegistrationsException on Handler interface

### ISSUE THREAD

**Issue by jafin** [Lavinski/Enexure.MicroBus#23]
Hello, 
first of not sure if this expected or not,  I was moving across some CommandHandlers from another lib to MicroBus.

I intially had code such as this:
```
public interface IFooHandler : Enexure.MicroBus.ICommandHandler<FooCommand> {} 
public class Foo : IFooHandler {}
```

which gives the **InvalidDuplicateRegistrationsException** in the Autofac buildup for FooCommand.
There is only one class that implements the interface.

Changing to below fixes it:

```
public class Foo : Enexure.MicroBus.ICommandHandler<FooCommand> {}
```

Should the duplicate registrationError occur for this?

**Comment by jafin** [comment]
The marker interface has no place in this setup anyhow, ignore me, the error just threw me initially.

**Comment by Lavinski** [comment]
Hey, glad you figured it out, you got me right as I left on holiday.
