### ISSUE TITLE
SomehowRecievedTaskWithoutResultException thrown when returning Task.CompletedTask

### ISSUE THREAD

**Issue by gkinsman** [Lavinski/Enexure.MicroBus#24]
Hey there,

It looks like you're throwing an exception if there's no result type on returned tasks, except that Task.Completed task has no result, and thus fails :). Perhaps we could allow the use of CompletedTask and just treat it as a void return?

Cheers,
George

**Comment by Lavinski** [comment]
I'll check it out! I'm assuming the issue is with Query or Command handlers returning the CompletedTask?

**Comment by Lavinski** [comment]
Found it, looks like it's an issue if the handlers are registered via `RegisterHandlers` which the tests don't currently cover (they use RegisterCommandHandler).
