### ISSUE TITLE
Enexure.MicroBus.Autofac version 3.6.2

### ISSUE THREAD

**Issue by jimmystridh** [Lavinski/Enexure.MicroBus#28]
Hi, are you able to publish a new version of Enexure.MicroBus.Autofac for version 3.6.2 with the latest fixes for .net core 2.1 as well ?

Thanks

**Comment by Lavinski** [comment]
Hi @jimmystridh 

Could you please provide some more detail? I'm not sure why the current packages would not work.

- Are you not able to use `Enexure.MicroBus.Autofac` with `.net core 2.1`?
- Can you clarify wat you mean by "publish a new version of Enexure.MicroBus.Autofac for version 3.6.2"?

Thanks!

**Comment by jimmystridh** [comment]
hi @Lavinski 
this was referring to the fact that Enexure.MicroBus.Autofac is only published on nuget with version 3.6.0, referring to Enexure.MicroBus version 3.6.0. So if you just refer Enexure.MicroBus.Autofac you're going to get an old version, but as I realized I could force Enexure.MicroBus to use 3.6.2 (though not sure if there are any other drawbacks with this).

Perhaps it's prudent to keep Enexure.MicroBus.Autofac version synced with Enexure.MicroBus ?

**Comment by Lavinski** [comment]
You can use the latest versions of all the packages together. Breaking changes are only present in major version bumps (e.g. 2.X.X -> 3.X.X).
