### ISSUE TITLE
ObjectDisposedException with Carter + MicroBus

### ISSUE THREAD

**Issue by gkinsman** [Lavinski/Enexure.MicroBus#30]
Hi there!

I've recently started using a Nancy-esque library called Carter for Web API's instead of plain MVC, and I've hit a bit of a snag when using the bus from its modules. I'm not quite sure what the problem is, but the symptom is that the `IDepenencyScope` that the bus uses to start a new scope to resolve handlers is already disposed. I saw there was another issue around multiple handlers, but this one has just a single event and single handler.

I've created a working reproduction here https://github.com/gkinsman/MicroBusRepro.

Any thoughts would be welcome!

**Comment by gkinsman** [comment]
Hmm, looking like this might be related to a Carter issue in which it isn't creating new module instances per request. Will keep this updated with my findings.

**Comment by gkinsman** [comment]
Fixed here https://github.com/CarterCommunity/Carter/pull/172

**Comment by Lavinski** [comment]
Glad you got to the bottom of it!
